name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.REPO_ACTOR }}
        password: ${{ secrets.REPO_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: ./chabcav-api/Dockerfile 
        push: true
        tags: ghcr.io/darwin-simbajon-dg/chabcav-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Railway
      uses: railwayapp/cli-action@v1
      with:
        command: up -d
        token: ${{ secrets.RAILWAY_TOKEN }}
